name: 06 - Contexts
run-name: 06 - Contexts | DEBUG-${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: "Check box for debug output."

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "JOB NAME: ${{github.job}}" 
          echo "SHA NAME: ${{github.sha}}"
          echo "REP NAME: ${{github.repository}}"
      - name: Display VARS
        run: |
            echo "VAR Value: ${{vars.MY_VAR}}"
          
