name: 06 - Contexts
run-name: 06 - Contexts | DEBUG-${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: "Check box for debug output."
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Information
        run: |
          echo "JOB NAME: ${{github.job}}" 
          echo "SHA NAME: ${{github.sha}}"
          echo "REP NAME: ${{github.repository}}"
      - name: Display VARS
        run: |
            echo "VAR Value: ${{vars.MY_VAR}}"
      - name: Display ENV vars
        run: |
          echo "Workflow env var: ${{env.MY_WORKFLOW_VAR }}" 
          echo "Workflow env var: ${{env.MY_JOB_VAR }}" 
