name: 09 - Functions

on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: "A bool checkbox"


jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Title
        run: |
          echo "PR Title: ${{github.event.pull_request.title}}"
      - name: Print PR lables
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels)}}
          EOF
      - name: Bug Step
        if: ${{ !cancelled() && contains(github.event.pull_reqest.title,'fix' ) }}
        run: |
          echo "I am a bug fix"
      - name: Sleep for 20 seconds
        run: |
          sleep 20
      - name: Failing step
        run: |
          echo "Exit with bad status code"
          exit 2
      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will print if previous step was a success"
      - name: I will exectuce
        if: ${{ failure() }}
        run: |
          echo "I will print if any previous steps failed"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print except when a previous step is cancelled"
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: |
          echo "I will print if a previous step is cancelled"
      
        

