name: 12 Working with outputs
on:
  workflow_dispatch:
    inputs:
      build_status:
        type: choice
        options:
          - success
          - failure
        default: success
        required: false
        description: "Build status"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}
    steps:
      - name: Print value of GITHUB_OUTPUT
        run:
          echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=success" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step Build"
          echo "$GITHUB_OUTPUT"
      - name: Step with fixed mistake
        run: |
          echo "mistake=true" >> "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step with mistake"
          echo "$GITHUB_OUTPUT"
  build-two:
    outputs:
      outputfrombuildtwo: ${{ steps.build-two.outputs.outputfrombuildtwo }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Just print output from build in job for build-two
        id: build-two
        run: |
          echo "outputfrombuildtwo=FROMBUILD_TWO" >> "$GITHUB_OUTPUT"
          echo ${{ needs.build-two.outputs.output1 }}
  

  build-three:
    outputs:
      build_three_output: ${{ steps.build-three.outputs.build_three_output }}
    runs-on: ubuntu-latest
    needs: [build, build-two]
    steps:
      - name: Just a build three outputs check
        id: build-three
        run: |
          echo "build_three_output=FROM_BUILD_THREE" >> "$GITHUB_OUTPUT"
          echo ${{ needs.build-three.outputs.build_three_output }}
  build-four:
    outputs:
      build-four-output: ${{ steps.build-four.outputs.build-four-output }}
    runs-on: ubuntu-latest
    needs: [build,build-two,build-three]
    steps:
      - name: Step four stuff echo all levels
        id: build-four
        run: |
          echo "build_four_stuff=FROM_BUILD_FOUR" >> "$GITHUB_OUTPUT"
          echo ${{ needs.build.outputs.output1 }}
          echo ${{ needs.build-two.outputs.outputfrombuildtwo }}
          echo ${{ needs.build-three.outputs.build-three-output }}
          echo ${{ needs.build-four.outputs.build-four-output }}
      - name: Check out pytest repo
        uses: actions/checkout@v4
        with:
          repository: 'marksimmons431/python_pytest'
          ref: 'main'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip upgrade --upgrade pip
      - name: Run pytest
        run: |
          pip install pytest
          pytest -sv .

  deploy:
    runs-on: ubuntu-latest
    needs: [build, build-two, build-three, build-four ]
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Print outputs from ALL build jobs
        run: |
          echo ${{ needs.build.outputs.output1 }}
          echo ${{ needs.build-two.outputs.outputfrombuildtwo }}
          echo ${{ needs.build-three.outputs.build_three_output }}
      - name: Deploy
        run: |
          echo "Deploying"
      - name: Print outputs from build-two job
        run: |
          echo ${{ needs.build-two.outputs.outputfrombuildtwo }}

