name: 12 Working with outputs
on:
  workflow_dispatch:
    inputs:
      build_status:
        type: choice
        options:
          - success
          - failure
        default: success
        required: false
        description: "Build status"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}
    steps:
      - name: Print value of GITHUB_OUTPUT
        run:
          echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=success" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step Build"
          echo "$GITHUB_OUTPUT"
      - name: Step with fixed mistake
        run: |
          echo "mistake=true" >> "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step with mistake"
          echo "$GITHUB_OUTPUT"
  build-two:
    outputs:
      outputfrombuildtwo: ${{ steps.build-two.outputs.outputfrombuildtwo }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Just print output from build in job for build-two
        run: |
          echo ${{ needs.build.outputs.output1 }}
  

  deploy:
    runs-on: ubuntu-latest
    needs: build-two
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Print outputs from build job
        run: |
          echo ${{ needs.build.outputs.output1 }}
          echo ${{ needs.build.outputs.output2 }}
      - name: Deploy
        run: |
          echo "Deploying"
      - name: Print outputs from build-two job
        run: |
          echo ${{ needs.build-two.outputs.outputfrombuildtwo }}

