name: 12 Working with outputs
on:
  workflow_dispatch:
    inputs:
      build_status:
        type: choice
        options:
          - success
          - failure
        default: success
        required: false
        description: "Build status"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print value of GITHUB_OUTPUT
        run:
          echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=success" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step Build"
          echo "$GITHUB_OUTPUT"
      - name: Step with mistake
        run: |
          echo "mistake=true" > "$GITHUB_OUTPUT"
          echo "====== BEGIN AGAIN ======"
          echo "Printing the output of OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "====== END AGAIN======"
          echo "Print the path step with mistake"
          echo "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Print Outputs
        run: |
          echo ${{ steps.build.outputs.output1 }}
      - name: Deploy
        run: |
          echo "Deploying"

